export const URL_DECL_PROP = new Set([
  "background",
  "background-image",
  "border",
  "border-image",
  "list-style",
  "list-style-image",
  "src",
]);
/**
 * @copyright https://github.com/jonschlinkert/self-closing-tags/blob/master/index.js
 */
export const SELF_CLOSE_TAG = new Set([
  "circle",
  "ellipse",
  "line",
  "path",
  "polygon",
  "polyline",
  "rect",
  "stop",
  "use",
  "area",
  "base",
  "br",
  "col",
  "command",
  "embed",
  "hr",
  "img",
  "input",
  "keygen",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
]);
